import { prisma } from '@/src/shared/lib/db'
import { calculatePayrollForUser } from '@/src/shared/lib/payment/calculate-payroll'
import {
  deletePayrollDocument as deletePayrollDocumentFromStorage,
  uploadPayrollDocument,
} from '@/src/shared/lib/storage/supabase-storage'
import { createNotification } from '@/src/features/notifications/lib/notification-service'

import {
  createPayrollDocument,
  createPayrollPeriod,
  deletePayrollDocumentsByPeriod,
  deletePayrollPeriod,
  getPayrollPeriodByOrgAndMonth,
  updatePayrollPeriod,
} from '@/src/entities/payroll/lib/payroll-repository'

async function loadPdfModules() {
  const [{ renderToBuffer }, { PayrollDocumentPdf }] = await Promise.all([
    import('@react-pdf/renderer'),
    import('@/src/features/payroll/ui/payroll-document-pdf'),
  ])
  return { renderToBuffer, PayrollDocumentPdf }
}

interface GeneratePayrollParams {
  organizationId: string
  month: number
  year: number
  force?: boolean
  actorId?: string
  isAutoGenerated?: boolean
  onProgress?: (current: number, total: number) => void
}

interface GeneratePayrollResult {
  periodId: string
  documentsGenerated: number
  totalAmount: number
  errors: string[]
}

export async function generatePayrollForOrganization(
  params: GeneratePayrollParams
): Promise<{ success: true; data: GeneratePayrollResult } | { success: false; error: string }> {
  const {
    organizationId,
    month,
    year,
    force = false,
    actorId,
    isAutoGenerated = false,
    onProgress,
  } = params

  const existing = await getPayrollPeriodByOrgAndMonth(organizationId, month, year)

  if (existing && !force)
    return {
      success: false,
      error: 'Ya existe una nómina para este período. Use la opción de forzar para regenerar.',
    }

  if (existing && force) {
    const docs = await prisma.payrollDocument.findMany({
      where: { payrollPeriodId: existing.id },
      select: { storagePath: true },
    })
    for (const doc of docs) await deletePayrollDocumentFromStorage(doc.storagePath)

    await deletePayrollDocumentsByPeriod(existing.id)
    await deletePayrollPeriod(existing.id, organizationId)
  }

  const org = await prisma.organization.findUniqueOrThrow({
    where: { id: organizationId },
    select: { currency: true, name: true, taxId: true, address: true },
  })

  const period = await createPayrollPeriod({
    organizationId,
    month,
    year,
    currency: org.currency,
    generatedBy: actorId ?? null,
    isAutoGenerated,
  })

  const usersWithContracts = await prisma.user.findMany({
    where: {
      organizationId,
      contracts: {
        some: {
          isActive: true,
          organizationId,
        },
      },
    },
    select: { id: true, name: true },
  })

  let documentsGenerated = 0
  let totalAmount = 0
  const errors: string[] = []
  const monthStr = String(month).padStart(2, '0')

  const { renderToBuffer, PayrollDocumentPdf } = await loadPdfModules()

  let processedCount = 0
  const totalUsers = usersWithContracts.length

  for (const user of usersWithContracts)
    try {
      processedCount++
      onProgress?.(processedCount, totalUsers)

      const result = await calculatePayrollForUser(user.id, organizationId, month, year)

      if (!result || result.totalAmount <= 0) continue

      const pdfElement = PayrollDocumentPdf({
        data: result,
        orgName: org.name,
        orgTaxId: org.taxId,
        orgAddress: org.address,
      })
      const pdfBuffer = await renderToBuffer(pdfElement)

      const uploadResult = await uploadPayrollDocument(
        organizationId,
        year,
        monthStr,
        user.id,
        period.id,
        Buffer.from(pdfBuffer)
      )

      if (!uploadResult.success || !uploadResult.storagePath) {
        errors.push(`${user.name}: ${uploadResult.error ?? 'Error de almacenamiento'}`)
        continue
      }

      const sanitizedName = user.name.toLowerCase().replace(/\s+/g, '-')
      const fileName = `nomina-${year}-${monthStr}-${sanitizedName}.pdf`

      await createPayrollDocument({
        payrollPeriodId: period.id,
        userId: user.id,
        organizationId,
        totalAmount: result.totalAmount,
        baseSalaryAmount: result.baseSalaryAmount,
        shiftsAmount: result.shiftsAmount,
        monthlyComponentsAmount: result.monthlyComponentsAmount,
        currency: org.currency,
        shiftsCount: result.shiftsCount,
        contractDaysInPeriod: result.contractDaysInPeriod,
        totalDaysInPeriod: result.totalDaysInPeriod,
        storagePath: uploadResult.storagePath,
        fileName,
      })

      documentsGenerated++
      totalAmount += result.totalAmount

      try {
        await createNotification({
          userId: user.id,
          actorId: actorId ?? user.id,
          organizationId,
          type: 'PAYROLL_DOCUMENT_AVAILABLE',
          title: `Tu documento de nómina de ${monthStr}/${year} está disponible`,
          actionUrl: '/dashboard/payroll',
        })
      } catch {}
    } catch (userError) {
      const msg = userError instanceof Error ? userError.message : 'Error desconocido'
      errors.push(`${user.name}: ${msg}`)
    }

  const status =
    errors.length === 0 ? 'COMPLETED' : documentsGenerated > 0 ? 'COMPLETED_WITH_ERRORS' : 'FAILED'

  await updatePayrollPeriod(period.id, {
    status,
    totalDocuments: documentsGenerated,
    totalAmount: Math.round(totalAmount * 100) / 100,
    generatedAt: new Date(),
    errorLog: errors.length > 0 ? JSON.stringify(errors) : null,
  })

  const adminUsers = await prisma.user.findMany({
    where: { organizationId, role: 'ADMIN_HR' },
    select: { id: true },
  })

  for (const admin of adminUsers)
    try {
      const notifType = status === 'FAILED' ? 'PAYROLL_GENERATION_FAILED' : 'PAYROLL_GENERATED'
      await createNotification({
        userId: admin.id,
        actorId: actorId ?? admin.id,
        organizationId,
        type: notifType,
        title:
          status === 'FAILED'
            ? `Error en generación de nómina ${monthStr}/${year}`
            : `Nómina generada: ${documentsGenerated} documentos para ${monthStr}/${year}`,
        actionUrl: '/dashboard/payroll',
      })
    } catch {}

  return {
    success: true,
    data: {
      periodId: period.id,
      documentsGenerated,
      totalAmount: Math.round(totalAmount * 100) / 100,
      errors,
    },
  }
}
