export const ICON_SEARCH_ALIASES: Record<string, string[]> = {
  Activity: ['actividad'],
  AlarmClock: ['alarma', 'reloj alarma', 'despertador'],
  Ambulance: ['ambulancia'],
  Baby: ['bebe', 'bebé', 'niño', 'niña'],
  BedDouble: ['cama', 'camas', 'descanso'],
  Building2: ['edificio', 'construcción', 'construccion'],
  Calendar: ['calendario'],
  CalendarClock: ['calendario reloj'],
  Camera: ['cámara', 'camara', 'foto'],
  Car: ['auto', 'coche', 'vehículo', 'vehiculo'],
  CheckCircle: ['check', 'correcto', 'éxito', 'exito'],
  Clock: ['reloj', 'hora', 'tiempo'],
  Cloud: ['nube', 'nubes'],
  CloudMoon: ['nube luna', 'noche nublada'],
  CloudRain: ['lluvia', 'lluvioso', 'llover'],
  CloudSun: ['sol nube', 'día nublado'],
  Coffee: ['café', 'cafe', 'taza'],
  Compass: ['brújula', 'brujula', 'compás', 'compas'],
  Crosshair: ['cruz', 'objetivo', 'punto'],
  Database: ['base datos', 'datos'],
  Droplet: ['gota', 'agua', 'líquido', 'liquido'],
  Flame: ['llama', 'fuego', 'calor'],
  FlaskConical: ['matraz', 'laboratorio', 'química', 'quimica'],
  Footprints: ['huellas', 'pasos', 'caminar'],
  Gauge: ['medidor', 'velocímetro', 'velocimetro'],
  Hammer: ['martillo', 'herramienta'],
  Headphones: ['auriculares', 'audífonos', 'audifonos', 'oídos', 'oidos'],
  Heart: ['corazón', 'corazon'],
  HeartPulse: ['corazón latido', 'corazon latido', 'pulso', 'salud'],
  Hospital: ['hospital', 'clínica', 'clinica', 'salud'],
  Lamp: ['lámpara', 'lampara', 'luz', 'iluminar'],
  Landmark: ['monumento', 'hito', 'punto referencia'],
  Layers: ['capas', 'apilar'],
  Lightbulb: ['bombilla', 'idea', 'bombillo'],
  Moon: ['luna', 'noche'],
  MoonStar: ['luna estrella', 'noche estrellada'],
  Mountain: ['montaña', 'montana', 'cerro'],
  Package: ['paquete', 'caja', 'envío', 'envio'],
  Palette: ['paleta', 'colores', 'pintura'],
  Pill: ['píldora', 'pildora', 'pastilla', 'medicamento'],
  Plane: ['avión', 'avion', 'vuelo'],
  Search: ['buscar', 'búsqueda', 'busqueda', 'lupa'],
  Shield: ['escudo', 'protección', 'proteccion'],
  ShieldCheck: ['escudo check', 'verificado'],
  Ship: ['barco', 'nave', 'mar'],
  Sparkles: ['brillos', 'estrellas', 'destacar'],
  Star: ['estrella'],
  Sun: ['sol', 'día', 'dia'],
  Sunrise: ['amanecer', 'salida sol'],
  Sunset: ['atardecer', 'puesta sol'],
  Stethoscope: ['estetoscopio', 'médico', 'medico'],
  Syringe: ['jeringa', 'inyección', 'inyeccion', 'vacuna'],
  Target: ['objetivo', 'meta', 'diana'],
  Tent: ['carpa', 'camping'],
  Thermometer: ['termómetro', 'termometro', 'temperatura'],
  Timer: ['temporizador', 'cronómetro', 'cronometro'],
  Tractor: ['tractor'],
  Train: ['tren'],
  TreePine: ['árbol', 'arbol', 'pino', 'tree'],
  Trophy: ['trofeo', 'premio', 'ganar'],
  Truck: ['camión', 'camion', 'camioneta'],
  Umbrella: ['paraguas', 'lluvia'],
  Users: ['usuarios', 'personas', 'equipo'],
  UtensilsCrossed: ['cubiertos', 'comida', 'restaurante'],
  Waves: ['olas', 'mar', 'agua'],
  Wind: ['viento'],
  Zap: ['rayo', 'electricidad', 'energía', 'energia'],
}

const ALL_ICONS = [
  'Activity',
  'AlarmClock',
  'Ambulance',
  'Baby',
  'BedDouble',
  'Building2',
  'Calendar',
  'CalendarClock',
  'Camera',
  'Car',
  'CheckCircle',
  'Clock',
  'Cloud',
  'CloudMoon',
  'CloudRain',
  'CloudSun',
  'Coffee',
  'Compass',
  'Crosshair',
  'Database',
  'Droplet',
  'Flame',
  'FlaskConical',
  'Footprints',
  'Gauge',
  'Hammer',
  'Headphones',
  'Heart',
  'HeartPulse',
  'Hospital',
  'Lamp',
  'Landmark',
  'Layers',
  'Lightbulb',
  'Moon',
  'MoonStar',
  'Mountain',
  'Package',
  'Palette',
  'Pill',
  'Plane',
  'Shield',
  'ShieldCheck',
  'Ship',
  'Sparkles',
  'Star',
  'Sun',
  'Sunrise',
  'Sunset',
  'Syringe',
  'Target',
  'Tent',
  'Thermometer',
  'Timer',
  'Tractor',
  'Train',
  'TreePine',
  'Trophy',
  'Truck',
  'Umbrella',
  'Users',
  'UtensilsCrossed',
  'Waves',
  'Wind',
  'Zap',
  'Stethoscope',
] as const

export const AREA_ICONS = ALL_ICONS

export const SHIFT_TYPE_ICONS = ALL_ICONS

export type AreaIcon = (typeof AREA_ICONS)[number]
export type ShiftTypeIcon = (typeof SHIFT_TYPE_ICONS)[number]
