'use server'

import type { Currency, PayrollPeriodStatus, Prisma } from '@prisma/client'

import { prisma } from '@/src/shared/lib/db'

import type {
  PayrollDocumentDetail,
  PayrollDocumentSummary,
  PayrollPeriodSummary,
  PayrollPeriodWithDocuments,
} from './types'

export async function createPayrollPeriod(data: {
  organizationId: string
  month: number
  year: number
  currency: Currency
  generatedBy?: string | null
  isAutoGenerated?: boolean
}) {
  return prisma.payrollPeriod.create({
    data: {
      organizationId: data.organizationId,
      month: data.month,
      year: data.year,
      currency: data.currency,
      generatedBy: data.generatedBy ?? null,
      isAutoGenerated: data.isAutoGenerated ?? false,
    },
  })
}

export async function updatePayrollPeriod(
  id: string,
  data: {
    status?: PayrollPeriodStatus
    totalDocuments?: number
    totalAmount?: number
    errorLog?: string | null
    generatedAt?: Date
  }
) {
  return prisma.payrollPeriod.update({
    where: { id },
    data,
  })
}

export async function getPayrollPeriod(
  id: string,
  organizationId: string
): Promise<PayrollPeriodWithDocuments | null> {
  const period = await prisma.payrollPeriod.findFirst({
    where: { id, organizationId },
    include: {
      documents: {
        include: {
          user: {
            select: { id: true, name: true, email: true },
          },
        },
        orderBy: { user: { name: 'asc' } },
      },
    },
  })

  if (!period) return null

  return {
    ...period,
    documents: period.documents as PayrollDocumentDetail[],
  }
}

export async function getPayrollPeriodByOrgAndMonth(
  organizationId: string,
  month: number,
  year: number
) {
  return prisma.payrollPeriod.findUnique({
    where: {
      organizationId_month_year: { organizationId, month, year },
    },
  })
}

export async function getPayrollPeriods(
  organizationId: string,
  year?: number
): Promise<PayrollPeriodSummary[]> {
  const periods = await prisma.payrollPeriod.findMany({
    where: {
      organizationId,
      ...(year ? { year } : {}),
    },
    select: {
      id: true,
      month: true,
      year: true,
      status: true,
      totalDocuments: true,
      totalAmount: true,
      currency: true,
      generatedAt: true,
      isAutoGenerated: true,
    },
    orderBy: [{ year: 'desc' }, { month: 'desc' }],
  })

  return periods
}

export async function createPayrollDocument(data: {
  payrollPeriodId: string
  userId: string
  organizationId: string
  totalAmount: number
  baseSalaryAmount: number
  shiftsAmount: number
  monthlyComponentsAmount: number
  currency: Currency
  shiftsCount: number
  contractDaysInPeriod: number
  totalDaysInPeriod: number
  storagePath: string
  fileName: string
}) {
  return prisma.payrollDocument.create({ data })
}

export async function deletePayrollDocument(id: string, organizationId: string) {
  return prisma.payrollDocument.delete({
    where: { id, organizationId },
  })
}

export async function getPayrollDocumentById(id: string, organizationId: string) {
  return prisma.payrollDocument.findFirst({
    where: { id, organizationId },
    include: {
      user: { select: { id: true, name: true, email: true } },
      payrollPeriod: { select: { month: true, year: true, status: true } },
    },
  })
}

export async function getPayrollDocuments(
  periodId: string,
  organizationId: string,
  options?: {
    userId?: string
    areaIds?: string[]
  }
): Promise<PayrollDocumentSummary[]> {
  const where: Prisma.PayrollDocumentWhereInput = {
    payrollPeriodId: periodId,
    organizationId,
  }

  if (options?.userId) where.userId = options.userId

  if (options?.areaIds)
    where.user = {
      userAreas: {
        some: { areaId: { in: options.areaIds } },
      },
    }

  const docs = await prisma.payrollDocument.findMany({
    where,
    include: {
      user: { select: { id: true, name: true, email: true } },
    },
    orderBy: { user: { name: 'asc' } },
  })

  return docs.map((doc: (typeof docs)[number]) => ({
    id: doc.id,
    userId: doc.userId,
    userName: doc.user.name,
    userEmail: doc.user.email,
    totalAmount: doc.totalAmount,
    baseSalaryAmount: doc.baseSalaryAmount,
    shiftsAmount: doc.shiftsAmount,
    monthlyComponentsAmount: doc.monthlyComponentsAmount,
    shiftsCount: doc.shiftsCount,
    currency: doc.currency,
    generatedAt: doc.generatedAt,
  }))
}

export async function deletePayrollDocumentsByPeriod(periodId: string) {
  return prisma.payrollDocument.deleteMany({
    where: { payrollPeriodId: periodId },
  })
}

export async function getFilteredPayrollPeriodSummaries(
  organizationId: string,
  year?: number,
  options?: { userId?: string; areaIds?: string[] }
): Promise<PayrollPeriodSummary[]> {
  const periods = await getPayrollPeriods(organizationId, year)

  if (!options) return periods

  const periodIds = periods.map((p) => p.id)
  if (periodIds.length === 0) return periods

  const where: Prisma.PayrollDocumentWhereInput = {
    payrollPeriodId: { in: periodIds },
    organizationId,
  }

  if (options.userId) where.userId = options.userId
  if (options.areaIds)
    where.user = {
      userAreas: { some: { areaId: { in: options.areaIds } } },
    }

  const aggregates = await prisma.payrollDocument.groupBy({
    by: ['payrollPeriodId'],
    where,
    _count: true,
    _sum: { totalAmount: true },
  })

  const aggMap = new Map(
    aggregates.map((a) => [
      a.payrollPeriodId,
      { count: a._count, total: a._sum.totalAmount ?? 0 },
    ])
  )

  return periods.map((period) => ({
    ...period,
    totalDocuments: aggMap.get(period.id)?.count ?? 0,
    totalAmount: aggMap.get(period.id)?.total ?? 0,
  }))
}

export async function deletePayrollPeriod(id: string, organizationId: string) {
  return prisma.payrollPeriod.delete({
    where: { id, organizationId },
  })
}
