import type { Currency, PayrollPeriodStatus } from '@prisma/client'

export interface PayrollPeriodSummary {
  id: string
  month: number
  year: number
  status: PayrollPeriodStatus
  totalDocuments: number
  totalAmount: number
  currency: Currency
  generatedAt: Date | null
  isAutoGenerated: boolean
}

export interface PayrollDocumentSummary {
  id: string
  userId: string
  userName: string
  userEmail: string
  totalAmount: number
  baseSalaryAmount: number
  shiftsAmount: number
  monthlyComponentsAmount: number
  shiftsCount: number
  currency: Currency
  generatedAt: Date
}

export interface PayrollPeriodWithDocuments {
  id: string
  organizationId: string
  month: number
  year: number
  status: PayrollPeriodStatus
  generatedBy: string | null
  generatedAt: Date | null
  totalDocuments: number
  totalAmount: number
  currency: Currency
  errorLog: string | null
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
  documents: PayrollDocumentDetail[]
}

export interface PayrollDocumentDetail {
  id: string
  payrollPeriodId: string
  userId: string
  organizationId: string
  totalAmount: number
  baseSalaryAmount: number
  shiftsAmount: number
  monthlyComponentsAmount: number
  currency: Currency
  shiftsCount: number
  contractDaysInPeriod: number
  totalDaysInPeriod: number
  storagePath: string
  fileName: string
  generatedAt: Date
  user: {
    id: string
    name: string
    email: string
  }
}
