import { NextResponse } from 'next/server'

import { env } from '@/src/shared/config/env.server'
import { prisma } from '@/src/shared/lib/db'
import { generatePayrollForOrganization } from '@/src/shared/lib/payment/generate-payroll-core'

interface OrgResult {
  organizationId: string
  organizationName: string
  status: 'success' | 'skipped' | 'failed'
  documentsGenerated?: number
  error?: string
}

function getPreviousMonth(): { month: number; year: number } {
  const now = new Date()
  
  const formatter = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Santiago',
    day: 'numeric',
    month: 'numeric',
    year: 'numeric',
  })
  const parts = formatter.formatToParts(now)
  const currentMonth = Number(parts.find((p) => p.type === 'month')?.value ?? now.getMonth() + 1)
  const currentYear = Number(parts.find((p) => p.type === 'year')?.value ?? now.getFullYear())

  if (currentMonth === 1) 
    return { month: 12, year: currentYear - 1 }
  
  return { month: currentMonth - 1, year: currentYear }
}

function getTodayInSantiago(): number {
  const formatter = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Santiago',
    day: 'numeric',
  })
  return Number(formatter.format(new Date()))
}

function getDaysInMonth(month: number, year: number): number {
  return new Date(year, month, 0).getDate()
}

export async function POST(request: Request) {
  
  const authHeader = request.headers.get('authorization')
  const expectedToken = env.CRON_SECRET

  if (!expectedToken) 
    return NextResponse.json({ error: 'CRON_SECRET not configured' }, { status: 500 })
  

  if (authHeader !== `Bearer ${expectedToken}`) 
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  

  const todayDay = getTodayInSantiago()
  const { month, year } = getPreviousMonth()
  const daysInCurrentMonth = getDaysInMonth(month + 1 <= 12 ? month + 1 : 1, month + 1 <= 12 ? year : year + 1)

  
  
  const organizations = await prisma.organization.findMany({
    where: {
      billingDay: { not: null },
      OR: [
        { billingDay: todayDay },
        
        ...(todayDay === daysInCurrentMonth
          ? [{ billingDay: { gt: daysInCurrentMonth } }]
          : []),
      ],
    },
    select: { id: true, name: true, billingDay: true },
  })

  const results: OrgResult[] = []

  for (const org of organizations) 
    try {
      const result = await generatePayrollForOrganization({
        organizationId: org.id,
        month,
        year,
        force: false,
        isAutoGenerated: true,
      })

      if (result.success) 
        results.push({
          organizationId: org.id,
          organizationName: org.name,
          status: 'success',
          documentsGenerated: result.data.documentsGenerated,
        })
       else 
        
        results.push({
          organizationId: org.id,
          organizationName: org.name,
          status: 'skipped',
          error: result.error,
        })
      
    } catch (error) {
      results.push({
        organizationId: org.id,
        organizationName: org.name,
        status: 'failed',
        error: error instanceof Error ? error.message : 'Unknown error',
      })
    }
  

  const summary = {
    date: new Date().toISOString(),
    todayDay,
    targetPeriod: `${month}/${year}`,
    organizationsMatched: organizations.length,
    processed: results.filter((r) => r.status === 'success').length,
    skipped: results.filter((r) => r.status === 'skipped').length,
    failed: results.filter((r) => r.status === 'failed').length,
    results,
  }

  return NextResponse.json(summary, { status: 200 })
}
